name: Xiaomi Community AutoTask

on:
  schedule:
    - cron: '6 16 * * *'  # 00:06 CST
    - cron: '9 16 * * *'
    - cron: '3 16 * * *'
    - cron: '7 16 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      COOKIE: ${{ secrets.COOKIE }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Xiaomi script
        run: python xiaomi.py
