name: Xiaomi Browser Automation Puppeteer

on:
  workflow_dispatch:
  schedule:
    - cron: '6 16 * * *'   # 00:03 CST
    - cron: '9 16 * * *'   # 00:06 CST
    - cron: '3 16 * * *'   # 00:07 CST
    - cron: '7 16 * * *'   # 00:09 CST

jobs:
  puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Xiaomi Puppeteer Script
        run: node xiaomi.js
        env:
          CUSERID: ${{ secrets.CUSERID }}
          TOKEN: ${{ secrets.TOKEN }}
